# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        go: [
          '^1.21.5',
        ]
        os: [
          ubuntu-latest,
          #ubuntu-20.04,
          macos-13,
          windows-2022,
        ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Build Pgx Example
        working-directory: ${{ github.workspace }}/sqlc/pgx
        run: go build -ldflags "-s -w" -v -o ../demo_pgx_${{ runner.os }}_${{ runner.arch }}
      - name: Upload Pgx Example
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: demo_pgx_${{ runner.os }}_${{ runner.arch }}
          path: ${{ github.workspace }}/sqlc/demo_pgx_${{ runner.os }}_${{ runner.arch }}

      - name: Build Pg Example
        working-directory: ${{ github.workspace }}/sqlc/pg
        run: go build -ldflags "-s -w" -v -o ../demo_pg_${{ runner.os }}_${{ runner.arch }}
      - name: Upload Pg Example
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: demo_pg_${{ runner.os }}_${{ runner.arch }}
          path: ${{ github.workspace }}/sqlc/demo_pg_${{ runner.os }}_${{ runner.arch }}

      - name: Build MySQL Example
        working-directory: ${{ github.workspace }}/sqlc/mysql
        run: go build -ldflags "-s -w" -v -o ../demo_mysql_${{ runner.os }}_${{ runner.arch }}
      - name: Upload MySQL Example
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: demo_mysql_${{ runner.os }}_${{ runner.arch }}
          path: ${{ github.workspace }}/sqlc/demo_mysql_${{ runner.os }}_${{ runner.arch }}

      - name: Build SQLite Example
        working-directory: ${{ github.workspace }}/sqlc/sqlite
        run: go build -ldflags "-s -w" -v -o ../demo_sqlite_${{ runner.os }}_${{ runner.arch }}
      - name: Upload SQLite Example
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: demo_sqlite_${{ runner.os }}_${{ runner.arch }}
          path: ${{ github.workspace }}/sqlc/demo_sqlite_${{ runner.os }}_${{ runner.arch }}

      - name: Build Mongo Example
        working-directory: ${{ github.workspace }}/mongo
        run: go build -ldflags "-s -w" -v -o ../demo_mongo_${{ runner.os }}_${{ runner.arch }}
      - name: Upload Mongo Example
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: demo_mongo_${{ runner.os }}_${{ runner.arch }}
          path: ${{ github.workspace }}/demo_mongo_${{ runner.os }}_${{ runner.arch }}
